FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

# set python to not to write .pyc files
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# install basic system dependencies required for potential runtime operations
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    libgomp1 \
    python3.11 \
    python3.11-dev \
    python3-pip \
    python3-venv \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

# Copy only requirements first to leverage Docker layer caching
COPY requirements.manager.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.manager.txt \
    --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124

COPY manager.py .

CMD ["sh", "-c", "uvicorn manager:app --host 0.0.0.0 --port ${MANAGER_PORT:-8001}"]
