FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

# set python to not to write .pyc files
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}


WORKDIR /app

# install basic system dependencies required for potential runtime operations
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-toolkit-12-4 \
    python3 \
    python3-pip \
    python3-venv
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/bin/python3 /usr/bin/python

# Copy only requirements first to leverage Docker layer caching
COPY requirements.manager.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.manager.txt \
    --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124

COPY manager.py .

CMD ["sh", "-c", "uvicorn manager:app --host 0.0.0.0 --port ${MANAGER_PORT:-8001}"]
